// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://atngqhvnzizufimblwmp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF0bmdxaHZueml6dWZpbWJsd21wIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5MDA2NDIsImV4cCI6MjA2NDQ3NjY0Mn0.zIvBpKufApxcrrBuc3CXKR8jdH6DonzXwtDanIaw6bU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);