
name: Build Android APK

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch: # Allows manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Setup Java 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      
    - name: Cache Gradle packages
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
      
    - name: Install dependencies
      run: npm ci
      
    - name: Build web app
      run: npm run build
      
    - name: Add Android platform if not already added
      run: |
        if [ ! -d "android" ]; then
          npx cap add android
          echo "Android platform added"
        else
          echo "Android platform already exists"
        fi
      
    - name: Sync Capacitor
      run: npx cap sync android
      
    - name: Grant execute permission for gradlew
      run: chmod +x android/gradlew
      
    - name: Clean Gradle cache
      run: |
        cd android
        ./gradlew clean
        
    - name: Build Android APK (Debug)
      run: |
        cd android
        ./gradlew assembleDebug --stacktrace --info
        
    - name: Build Android APK (Release)
      run: |
        cd android
        ./gradlew assembleRelease --stacktrace --info
      continue-on-error: true
        
    - name: Upload Debug APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: gooddeeds-vpn-debug-apk
        path: android/app/build/outputs/apk/debug/app-debug.apk
        retention-days: 30
        
    - name: Upload Release APK artifact
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: gooddeeds-vpn-release-apk
        path: android/app/build/outputs/apk/release/app-release-unsigned.apk
        retention-days: 90
        
    - name: Build summary
      run: |
        echo "## Build Results" >> $GITHUB_STEP_SUMMARY
        echo "### APK Files Generated:" >> $GITHUB_STEP_SUMMARY
        find android/app/build/outputs/apk -name "*.apk" -exec ls -la {} \; >> $GITHUB_STEP_SUMMARY || echo "No APK files found" >> $GITHUB_STEP_SUMMARY
